### ISSUE TITLE
Missing dependency: immutabledict

### ISSUE THREAD

**Issue by k-c-p** [Langenfeld/py-gitea#25]
py-gitea uses `immutabledict` but does not list it a setup.py, resulting in an import errror:

Reproducable:

- Setup venv
 ```
python3 -m venv venv
venv/bin/pip install py-gitea
```
-  Resulting venv
```
$ venv/bin/pip list
Package            Version
------------------ ----------
certifi            2023.11.17
charset-normalizer 3.3.2
frozendict         2.4.0
idna               3.6
pip                23.3
py-gitea           0.2.7
requests           2.31.0
setuptools         68.1.2
urllib3            2.1.0
```
- Try import
```shell
$ venv/bin/python
Python 3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gitea import Gitea, Organization
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.11/site-packages/gitea/__init__.py", line 1, in <module>
    from .gitea import (
  File "/tmp/venv/lib/python3.11/site-packages/gitea/gitea.py", line 5, in <module>
    from immutabledict import immutabledict
ModuleNotFoundError: No module named 'immutabledict'
```
- Install missing dep `immutabledict`
```
$ venv/bin/pip list
Package            Version
------------------ ----------
certifi            2023.11.17
charset-normalizer 3.3.2
frozendict         2.4.0
idna               3.6
immutabledict      4.1.0
pip                23.3
py-gitea           0.2.7
requests           2.31.0
setuptools         68.1.2
urllib3            2.1
```
- Try import again
```
$ venv/bin/python
Python 3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gitea import Gitea, Organization
>>> 
```

**Comment by k-c-p** [comment]
Not an issue anymore in version 0.2.8
